1 - Bibliotecas

In [23]:
import pandas as pd
import openpyxl
import os
import glob

2 - Lendo Arquivo Contratos.xlsx

In [24]:
input_path = "../Data/1 - Raw/Contratos/Contratos.xlsx"
output_path = "../Data/2 - Bronze"

df_bruto = pd.read_excel(input_path, dtype=str)

3 - Data Frame contratos bruto

In [25]:
df_bruto

,Cód Funcionário,Funcionário,Sexo,Data Admissão,Cód Cargo,Cargo,Data Cargo,Cód Escala,Escala,Cód C.Custo,...,Nacionalidade,Cód Raça,Raça,Valor Salário,Data Salário,Cód Situação,Situação,Data Afastamento,Cód Causa Afastamento,Causa Afastamento
0,1,MINAS MADUREIRA FORTALEZA,M,01/07/2002,249,AUXILIAR DE SERVIÇOS DE GERAIS,01/07/2002,1,08-18 seg-qui / 08-17 sex ADM,18,...,Brasileiro,4,Parda,648.49,01/03/2004,7,Demitido,28/04/2004,2,Inic.Empresa s/ Justa Causa
1,2,ROSEMARIO OUTEIRO SAMPAIO,M,06/08/2002,260,CONTROLER EM GERAL,06/08/2002,1,08-18 seg-qui / 08-17 sex ADM,2,...,Brasileiro,1,Branca,4775.21,01/10/2003,7,Demitido,2003-01-23 00:00:00,2,Inic.Empresa s/ Justa Causa
2,3,ELIZIARO VIANA MATOS,M,01/01/2002,001001,DIRETOR GERAL,01/10/2017,1,08-18 seg-qui / 08-17 sex ADM,L101001,...,Brasileiro,1,Branca,44044.96,01/06/2017,7,Demitido,02/04/2018,2,Inic.Empresa s/ Justa Causa
3,4,EDGAR FAGUNDES FERREIRA,M,01/09/2002,159,VENDEDOR EM GERAL,01/09/2002,1,08-18 seg-qui / 08-17 sex ADM,2,...,Brasileiro,4,Parda,1632.12,01/09/2002,7,Demitido,02/05/2003,2,Inic.Empresa s/ Justa Causa
4,5,ADREN NAVES NASCIMENTO,M,14/03/2003,307,SUPERVISOR COMPRAS DE BLOCOS,01/07/2009,1,08-18 seg-qui / 08-17 sex ADM,L401006,...,Brasileiro,1,Branca,6709.07,01/05/2014,7,Demitido,28/11/2014,2,Inic.Empresa s/ Justa Causa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
855,1745,WEIK PEDROSO MORAES,M,19/10/2016,044002,CONTROLADOR DE ESTOQUE I,10/06/2020,14,08-18 seg-qui / 08-17 sex PRO,L402101,...,Brasileiro,1,Branca,2159.26,03/05/2019,1,Trabalhando,00/00/0000,0,NaN
856,1746,LUDMILIA NEGRETE FREITAS,F,08/07/2020,011001,APRENDIZ SERV.ADMINISTRATIVO,08/07/2020,38,14:00 as 18:00 aprendizagem,L301002,...,Brasileiro,1,Branca,522.5,08/07/2020,1,Trabalhando,00/00/0000,0,NaN
857,1747,VERONICIO CUNHA BRASILIENSE,M,08/07/2020,011001,APRENDIZ SERV.ADMINISTRATIVO,08/07/2020,38,14:00 as 18:00 aprendizagem,L102002,...,Brasileiro,1,Branca,522.5,08/07/2020,1,Trabalhando,00/00/0000,0,NaN
858,1748,MARIGELSON ZAMPOL CARMO,M,08/07/2020,011001,APRENDIZ SERV.ADMINISTRATIVO,08/07/2020,38,14:00 as 18:00 aprendizagem,L102001,...,Brasileiro,4,Parda,522.5,08/07/2020,1,Trabalhando,00/00/0000,0,NaN
859,1749,CLENILSO ADÃES CURADO,M,08/07/2020,011001,APRENDIZ SERV.ADMINISTRATIVO,08/07/2020,38,14:00 as 18:00 aprendizagem,L402011,...,Brasileiro,4,Parda,522.5,08/07/2020,1,Trabalhando,00/00/0000,0,NaN

4 - Criando a dimensão funcionário

In [26]:
colunas_funcionario = ['Cód Funcionário', 'Funcionário', 'Sexo', 'Nacionalidade', 
                'Raça', 'Estado Civil', 'Escolaridade', 'Data Nascimento']

dim_funcionario = df_bruto[colunas_funcionario].drop_duplicates(subset=['Cód Funcionário']).reset_index(drop=True)

dim_funcionario

,Cód Funcionário,Funcionário,Sexo,Nacionalidade,Raça,Estado Civil,Escolaridade,Data Nascimento
0,1,MINAS MADUREIRA FORTALEZA,M,Brasileiro,Parda,Solteiro,Ensino Médio Incompleto,30/06/1985
1,2,ROSEMARIO OUTEIRO SAMPAIO,M,Brasileiro,Branca,Casado,Superior Completo,27/10/1962
2,3,ELIZIARO VIANA MATOS,M,Brasileiro,Branca,Casado,Superior Incompleto,17/02/1972
3,4,EDGAR FAGUNDES FERREIRA,M,Brasileiro,Parda,Solteiro,Ensino Médio Completo,00/00/0000
4,5,ADREN NAVES NASCIMENTO,M,Brasileiro,Branca,Casado,Ensino Médio Completo,24/01/1975
...,...,...,...,...,...,...,...,...
855,1745,WEIK PEDROSO MORAES,M,Brasileiro,Branca,Divorciado,Ensino Médio Incompleto,27/01/1978
856,1746,LUDMILIA NEGRETE FREITAS,F,Brasileiro,Branca,Solteiro,Ensino Médio Incompleto,14/03/2003
857,1747,VERONICIO CUNHA BRASILIENSE,M,Brasileiro,Branca,Solteiro,Ensino Médio Incompleto,12/02/2005
858,1748,MARIGELSON ZAMPOL CARMO,M,Brasileiro,Parda,Solteiro,Ensino Médio Completo,04/05/2004
859,1749,CLENILSO ADÃES CURADO,M,Brasileiro,Parda,Solteiro,Ensino Médio Incompleto,23/05/2003

5 - Criando a dimensão cargo

In [27]:
dim_cargo = df_bruto[['Cód Cargo', 'Cargo']].drop_duplicates().reset_index(drop=True)

#dim_cargo

6 - Criando a dimensão Centro de Custo

In [28]:
dim_centro_custo = df_bruto[['Cód C.Custo', 'Centro Custo']].drop_duplicates().reset_index(drop=True)

#dim_centro_custo

7 - Criando a dimensão Escala

In [29]:
dim_escala = df_bruto[['Cód Escala', 'Escala']].drop_duplicates().reset_index(drop=True)

#dim_escala

8 - Criando a dimensão Tipo Contrato

In [30]:
dim_tipo_contrato = df_bruto[['Cód T. Contrato', 'Tipo Contrato']].drop_duplicates().reset_index(drop=True)

9 - Criando a dimensão Situação

In [31]:
dim_situacao = df_bruto[['Cód Situação', 'Situação']].drop_duplicates().reset_index(drop=True)

10 - Criando a fato contrato

In [32]:
colunas_fato = [
    'Cód Funcionário',      
    'Cód Cargo',           
    'Cód Escala',           
    'Cód C.Custo',          
    'Cód T. Contrato',      
    'Cód Situação',        
    'Data Admissão', 
    'Valor Salário', 
    'Data Salário', 
    'Data Afastamento'
]

fato_contrato = df_bruto[colunas_fato].copy()

#fato_contrato

11 - Salvando as dimensões e fato contratos em arquivo parquet na camada bronze

In [33]:
dim_funcionario.to_parquet(os.path.join(output_path, "dim_funcionario.parquet"), index=False)

dim_cargo.to_parquet(os.path.join(output_path, "dim_cargo.parquet"), index=False)

dim_centro_custo.to_parquet(os.path.join(output_path, "dim_centro_custo.parquet"), index=False)

dim_escala.to_parquet(os.path.join(output_path, "dim_escala.parquet"), index=False)

dim_situacao.to_parquet(os.path.join(output_path, "dim_situacao.parquet"), index=False)

dim_tipo_contrato.to_parquet(os.path.join(output_path, "dim_tipo_contrato.parquet"), index=False)

fato_contrato.to_parquet(os.path.join(output_path, "fato_contrato.parquet"), index=False)

12 - Lendo pasta Ficha Financeira, onde os arquivos de ficha financeira estão.

In [38]:
input_path_ficha_financeira = "../Data/1 - Raw/Ficha Financeira"

padrao_busca = os.path.join(input_path_ficha_financeira, '*.csv') #Definindo uma regra para a busca dos arquvios csv

arquivos_csv = glob.glob(padrao_busca) #Utilizando o glob para listar os arquivos que batem com o padrão de busca

lista_dfs = [] #Cria uma lista vazia para armazenar cada DataFrame individual temporariamente


print(f"Arquivos encontrados: {len(arquivos_csv)}")

#df_teste = pd.read_csv(arquivos_csv[0], sep=';', encoding='latin1')
#df_teste.head() # Exibe as 5 primeiras linhas do teste

for arquivo in arquivos_csv:

    df_ficha_financeira_temp = pd.read_csv(arquivo, sep=';', encoding='latin1')
    
    lista_dfs.append(df_ficha_financeira_temp)

fato_ficha_financeira = pd.concat(lista_dfs, ignore_index=True)

Arquivos encontrados: 6

12 - Salvando a fato ficha financeira em arquivo parquet na camada bronze

In [39]:
fato_ficha_financeira.to_parquet(os.path.join(output_path, "fato_ficha_financeira.parquet"), index=False)