1 - Bibliotecas

In [14]:
import pandas as pd
import openpyxl
import os

2 - Lendo arquivo dim_tipo_contrato

In [15]:
input_path = "../Data/2 - Bronze/dim_tipo_contrato.parquet"
output_path = "../Data/3 - Silver"


df = pd.read_parquet(input_path)

df

  Cód T. Contrato Tipo Contrato
0               1     Empregado
1               2       Diretor
2               5    Estagiário
3               6      Aprendiz

3 - Renomeando colunas

In [16]:
df = df.rename(columns={'Cód T. Contrato': 'cod_tipo_contrato', 
                        'Tipo Contrato': 'tipo_contrato',})

4 - Tipando as colunas do data frame

In [17]:
tipos = { 
    'cod_tipo_contrato': 'Int64',
    'tipo_contrato': 'string',
}

df = df.astype(tipos)

5 - Garantir que os IDs das situações sempre sejam numéricos

In [18]:
df['cod_tipo_contrato'] = pd.to_numeric(df['cod_tipo_contrato'], errors='coerce')

6 - Padronizando os dados do tipo string para maíusculo

In [19]:
colunas_texto = df.select_dtypes(include=['string']).columns

for col in colunas_texto:
    df[col] = df[col].str.upper().str.strip()

df

   cod_tipo_contrato tipo_contrato
0                  1     EMPREGADO
1                  2       DIRETOR
2                  5    ESTAGIÁRIO
3                  6      APRENDIZ

7 - Enviando dim_tipo_contrato tratada para a camada silver

In [20]:
df.to_parquet(os.path.join(output_path, "dim_tipo_contrato.parquet"), index=False)