1 - Bibliotecas

In [14]:
import pandas as pd
import openpyxl
import os

2 - Lendo arquivo fato_contrato

In [15]:
input_path = "../Data/2 - Bronze/fato_contrato.parquet"
output_path = "../Data/3 - Silver"


df = pd.read_parquet(input_path)

df

,Cód Funcionário,Cód Cargo,Cód Escala,Cód C.Custo,Cód T. Contrato,Cód Situação,Data Admissão,Valor Salário,Data Salário,Data Afastamento
0,1,249,1,18,1,7,01/07/2002,648.49,01/03/2004,28/04/2004
1,2,260,1,2,1,7,06/08/2002,4775.21,01/10/2003,2003-01-23 00:00:00
2,3,001001,1,L101001,2,7,01/01/2002,44044.96,01/06/2017,02/04/2018
3,4,159,1,2,1,7,01/09/2002,1632.12,01/09/2002,02/05/2003
4,5,307,1,L401006,1,7,14/03/2003,6709.07,01/05/2014,28/11/2014
...,...,...,...,...,...,...,...,...,...,...
855,1745,044002,14,L402101,1,1,19/10/2016,2159.26,03/05/2019,00/00/0000
856,1746,011001,38,L301002,6,1,08/07/2020,522.5,08/07/2020,00/00/0000
857,1747,011001,38,L102002,6,1,08/07/2020,522.5,08/07/2020,00/00/0000
858,1748,011001,38,L102001,6,1,08/07/2020,522.5,08/07/2020,00/00/0000
859,1749,011001,38,L402011,6,1,08/07/2020,522.5,08/07/2020,00/00/0000

3 - Renomeando colunas

In [16]:
df = df.rename(columns={'Cód Funcionário': 'cod_funcionario', 
                        'Cód Cargo': 'cod_cargo',
                        'Cód Escala': 'cod_escala',
                        'Cód C.Custo': 'cod_centro_custo',
                        'Cód T. Contrato': 'cod_tipo_contrato',
                        'Cód Situação': 'cod_situacao',
                        'Data Admissão': 'data_admissao',
                        'Data Salário': 'data_salario',
                        'Data Afastamento': 'data_afastamento',
                        'Valor Salário': 'valor_salario',})

4 - Tipando colunas do data frame

In [17]:
tipos = { 
    'cod_funcionario': 'Int64',
    'cod_cargo': 'Int64',
    'cod_escala': 'Int64',
    'cod_centro_custo': 'string',
    'cod_tipo_contrato': 'Int64',
    'cod_situacao': 'Int64',
}

df = df.astype(tipos)

df['data_admissao'] = pd.to_datetime(df['data_admissao'], format='%d/%m/%Y', errors='coerce')
df['data_salario'] = pd.to_datetime(df['data_salario'], format='%d/%m/%Y', errors='coerce')
df['data_afastamento'] = pd.to_datetime(df['data_afastamento'], format='%d/%m/%Y', errors='coerce')

df

,cod_funcionario,cod_cargo,cod_escala,cod_centro_custo,cod_tipo_contrato,cod_situacao,data_admissao,valor_salario,data_salario,data_afastamento
0,1,249,1,18,1,7,2002-07-01,648.49,2004-03-01,2004-04-28
1,2,260,1,2,1,7,2002-08-06,4775.21,2003-10-01,NaT
2,3,1001,1,L101001,2,7,2002-01-01,44044.96,2017-06-01,2018-04-02
3,4,159,1,2,1,7,2002-09-01,1632.12,2002-09-01,2003-05-02
4,5,307,1,L401006,1,7,2003-03-14,6709.07,2014-05-01,2014-11-28
...,...,...,...,...,...,...,...,...,...,...
855,1745,44002,14,L402101,1,1,2016-10-19,2159.26,2019-05-03,NaT
856,1746,11001,38,L301002,6,1,2020-07-08,522.5,2020-07-08,NaT
857,1747,11001,38,L102002,6,1,2020-07-08,522.5,2020-07-08,NaT
858,1748,11001,38,L102001,6,1,2020-07-08,522.5,2020-07-08,NaT
859,1749,11001,38,L402011,6,1,2020-07-08,522.5,2020-07-08,NaT

5 - Garantir que os IDs dos funcionarios sempre sejam numéricos

In [18]:
df['cod_funcionario'] = pd.to_numeric(df['cod_funcionario'], errors='coerce')

6 - Padronizando os dados do tipo string para maísculo

In [ ]:
colunas_texto = df.select_dtypes(include=['string']).columns

for col in colunas_texto:
    df[col] = df[col].str.upper().str.strip()

df

,cod_funcionario,cod_cargo,cod_escala,cod_centro_custo,cod_tipo_contrato,cod_situacao,data_admissao,valor_salario,data_salario,data_afastamento
0,1,249,1,18,1,7,2002-07-01,648.49,2004-03-01,2004-04-28
1,2,260,1,2,1,7,2002-08-06,4775.21,2003-10-01,NaT
2,3,1001,1,L101001,2,7,2002-01-01,44044.96,2017-06-01,2018-04-02
3,4,159,1,2,1,7,2002-09-01,1632.12,2002-09-01,2003-05-02
4,5,307,1,L401006,1,7,2003-03-14,6709.07,2014-05-01,2014-11-28
...,...,...,...,...,...,...,...,...,...,...
855,1745,44002,14,L402101,1,1,2016-10-19,2159.26,2019-05-03,NaT
856,1746,11001,38,L301002,6,1,2020-07-08,522.5,2020-07-08,NaT
857,1747,11001,38,L102002,6,1,2020-07-08,522.5,2020-07-08,NaT
858,1748,11001,38,L102001,6,1,2020-07-08,522.5,2020-07-08,NaT
859,1749,11001,38,L402011,6,1,2020-07-08,522.5,2020-07-08,NaT

7 - Enviando fato_contrato tratada para a camada silver

In [20]:
df.to_parquet(os.path.join(output_path, "fato_contrato.parquet"), index=False)