1 - Bibliotecas

In [9]:
import pandas as pd
import openpyxl
import os

2 - Lendo arquivo dim_funcionario.parquet

In [10]:
input_path = "../Data/2 - Bronze/dim_funcionario.parquet"
output_path = "../Data/3 - Silver"


df = pd.read_parquet(input_path)

df

,Cód Funcionário,Funcionário,Sexo,Nacionalidade,Raça,Estado Civil,Escolaridade,Data Nascimento
0,1,MINAS MADUREIRA FORTALEZA,M,Brasileiro,Parda,Solteiro,Ensino Médio Incompleto,30/06/1985
1,2,ROSEMARIO OUTEIRO SAMPAIO,M,Brasileiro,Branca,Casado,Superior Completo,27/10/1962
2,3,ELIZIARO VIANA MATOS,M,Brasileiro,Branca,Casado,Superior Incompleto,17/02/1972
3,4,EDGAR FAGUNDES FERREIRA,M,Brasileiro,Parda,Solteiro,Ensino Médio Completo,00/00/0000
4,5,ADREN NAVES NASCIMENTO,M,Brasileiro,Branca,Casado,Ensino Médio Completo,24/01/1975
...,...,...,...,...,...,...,...,...
855,1745,WEIK PEDROSO MORAES,M,Brasileiro,Branca,Divorciado,Ensino Médio Incompleto,27/01/1978
856,1746,LUDMILIA NEGRETE FREITAS,F,Brasileiro,Branca,Solteiro,Ensino Médio Incompleto,14/03/2003
857,1747,VERONICIO CUNHA BRASILIENSE,M,Brasileiro,Branca,Solteiro,Ensino Médio Incompleto,12/02/2005
858,1748,MARIGELSON ZAMPOL CARMO,M,Brasileiro,Parda,Solteiro,Ensino Médio Completo,04/05/2004
859,1749,CLENILSO ADÃES CURADO,M,Brasileiro,Parda,Solteiro,Ensino Médio Incompleto,23/05/2003

3 - Renomeando colunas

In [11]:
df = df.rename(columns={'Cód Funcionário': 'cod_funcionario', 
                        'Funcionário': 'funcionario',
                       'Sexo': 'sexo',
                       'Nacionalidade': 'nacionalidade',
                       'Raça': 'raca',
                       'Estado Civil': 'estado_civil',
                       'Escolaridade': 'escolaridade',
                       'Data Nascimento': 'data_nascimento'})

4 - Tipando as colunas do data frame e tratando datas fora do padrão

In [12]:
tipos = { 
    'cod_funcionario': 'Int64',
    'funcionario': 'string',
    'sexo': 'string',
    'nacionalidade': 'string',
    'raca': 'string',
    'estado_civil': 'string',
    'escolaridade': 'string',
}

df = df.astype(tipos)

df['data_nascimento'] = pd.to_datetime(df['data_nascimento'], format='%d/%m/%Y', errors='coerce')

5 - Garantir que os IDs dos funcionarios sempre sejam numéricos

In [13]:
df['cod_funcionario'] = pd.to_numeric(df['cod_funcionario'], errors='coerce')

6 - Padronizando os dados do tipo string para maíusculo

In [14]:
colunas_texto = df.select_dtypes(include=['string']).columns

for col in colunas_texto:
    df[col] = df[col].str.upper().str.strip()

df

,cod_funcionario,funcionario,sexo,nacionalidade,raca,estado_civil,escolaridade,data_nascimento
0,1,MINAS MADUREIRA FORTALEZA,M,BRASILEIRO,PARDA,SOLTEIRO,ENSINO MÉDIO INCOMPLETO,1985-06-30
1,2,ROSEMARIO OUTEIRO SAMPAIO,M,BRASILEIRO,BRANCA,CASADO,SUPERIOR COMPLETO,1962-10-27
2,3,ELIZIARO VIANA MATOS,M,BRASILEIRO,BRANCA,CASADO,SUPERIOR INCOMPLETO,1972-02-17
3,4,EDGAR FAGUNDES FERREIRA,M,BRASILEIRO,PARDA,SOLTEIRO,ENSINO MÉDIO COMPLETO,NaT
4,5,ADREN NAVES NASCIMENTO,M,BRASILEIRO,BRANCA,CASADO,ENSINO MÉDIO COMPLETO,1975-01-24
...,...,...,...,...,...,...,...,...
855,1745,WEIK PEDROSO MORAES,M,BRASILEIRO,BRANCA,DIVORCIADO,ENSINO MÉDIO INCOMPLETO,1978-01-27
856,1746,LUDMILIA NEGRETE FREITAS,F,BRASILEIRO,BRANCA,SOLTEIRO,ENSINO MÉDIO INCOMPLETO,2003-03-14
857,1747,VERONICIO CUNHA BRASILIENSE,M,BRASILEIRO,BRANCA,SOLTEIRO,ENSINO MÉDIO INCOMPLETO,2005-02-12
858,1748,MARIGELSON ZAMPOL CARMO,M,BRASILEIRO,PARDA,SOLTEIRO,ENSINO MÉDIO COMPLETO,2004-05-04
859,1749,CLENILSO ADÃES CURADO,M,BRASILEIRO,PARDA,SOLTEIRO,ENSINO MÉDIO INCOMPLETO,2003-05-23

7 - Enviando dim_funcionario tratada para a camada silver

In [15]:
df.to_parquet(os.path.join(output_path, "dim_funcionario.parquet"), index=False)